const flowConfig = {
  "id": "f989c3bc-da3c-4021-8b19-f527920ba0a4",
  "name": "Pitiful Eventide",
  "nodes": [
    {
      "id": "triggerNode_1",
      "data": {
        "modes": {},
        "nodeId": "graphqlNode",
        "values": {
          "nodeName": "API Request",
          "responeType": "realtime",
          "advance_schema": "{\"sampleInput\":\"string\"}"
        },
        "trigger": true
      },
      "type": "triggerNode",
      "measured": {
        "width": 216,
        "height": 93
      },
      "position": {
        "x": 225,
        "y": 0
      },
      "selected": false
    },
    {
      "id": "addNode_346",
      "data": {
        "label": "addNode node",
        "modes": {},
        "nodeId": "addNode",
        "values": {}
      },
      "type": "addNode",
      "measured": {
        "width": 216,
        "height": 100
      },
      "position": {
        "x": 450,
        "y": 260
      }
    },
    {
      "id": "addNode_547",
      "data": {
        "label": "addNode node",
        "modes": {},
        "nodeId": "addNode",
        "values": {},
        "condition": "Invoice"
      },
      "type": "addNode",
      "measured": {
        "width": 216,
        "height": 100
      },
      "position": {
        "x": 0,
        "y": 260
      }
    },
    {
      "id": "docClassifierNode_960",
      "data": {
        "label": "Doc Classifier",
        "modes": [],
        "nodeId": "docClassifierNode",
        "values": {
          "id": "docClassifierNode_960",
          "nodeName": "Doc Classifier",
          "classifier": [
            {
              "label": "Invoice",
              "value": "docClassifierNode_960-addNode_547",
              "description": "This is for invoice generated by a billing system. "
            },
            {
              "label": "Classifier 2",
              "value": "docClassifierNode_960-addNode_346",
              "description": "This is for a loan approval document, "
            }
          ],
          "documentUrl": "https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://slicedinvoices.com/pdf/wordpress-pdf-invoice-plugin-sample.pdf&ved=2ahUKEwiJyPOy8pKUAxXLcmwGHWCfH6oQFnoECBUQAQ&usg=AOvVaw3LuLujg7LXhoXgwlL1dS4o",
          "ocrModelName": [
            {
              "type": "ocr/document",
              "params": {},
              "configName": "configA",
              "model_name": "mistral-document-ai-2512",
              "credentialId": "9a254862-0450-462e-bab1-cb201ded9084",
              "provider_name": "azure-ai-foundry",
              "credential_name": "popp"
            }
          ],
          "embeddingModelName": {
            "type": "embedder/text",
            "params": {},
            "model_name": "gemini/gemini-embedding-exp-03-07",
            "credentialId": "78b4d60b-c6a3-497e-81dd-f3321c361207",
            "provider_name": "gemini",
            "credential_name": "gemini"
          },
          "enhanceDescriptions": true,
          "generativeModelName": [
            {
              "type": "generator/text",
              "params": {},
              "configName": "configA",
              "model_name": "azure_ai/mistral-large",
              "credentialId": "a6d84738-1f51-4fad-a3fc-966581d4f5a8",
              "provider_name": "azure-ai-foundry",
              "credential_name": "ana"
            }
          ]
        }
      },
      "type": "agentClassifierNode",
      "measured": {
        "width": 216,
        "height": 93
      },
      "position": {
        "x": 225,
        "y": 130
      },
      "selected": true
    },
    {
      "id": "responseNode_triggerNode_1",
      "data": {
        "label": "Response",
        "nodeId": "graphqlResponseNode",
        "values": {
          "headers": "{\"content-type\":\"application/json\"}",
          "retries": "0",
          "nodeName": "API Response",
          "webhookUrl": "",
          "retry_delay": "0",
          "outputMapping": "{}"
        },
        "condition": "Invoice",
        "isResponseNode": true
      },
      "type": "responseNode",
      "measured": {
        "width": 216,
        "height": 93
      },
      "position": {
        "x": 225,
        "y": 390
      }
    }
  ],
  "edges": [
    {
      "id": "triggerNode_1-docClassifierNode_960",
      "type": "defaultEdge",
      "source": "triggerNode_1",
      "target": "docClassifierNode_960",
      "sourceHandle": "bottom",
      "targetHandle": "top"
    },
    {
      "id": "docClassifierNode_960-addNode_547",
      "data": {
        "condition": "Invoice",
        "branchName": "Classifier 1"
      },
      "type": "agentClassifierEdge",
      "source": "docClassifierNode_960",
      "target": "addNode_547",
      "sourceHandle": "bottom",
      "targetHandle": "top"
    },
    {
      "id": "docClassifierNode_960-addNode_346",
      "data": {
        "condition": "Classifier 2",
        "branchName": "Classifier 2"
      },
      "type": "agentClassifierEdge",
      "source": "docClassifierNode_960",
      "target": "addNode_346",
      "sourceHandle": "bottom",
      "targetHandle": "top"
    },
    {
      "id": "addNode_547-responseNode_triggerNode_1",
      "type": "defaultEdge",
      "source": "addNode_547",
      "target": "responseNode_triggerNode_1",
      "sourceHandle": "bottom",
      "targetHandle": "top"
    },
    {
      "id": "addNode_346-responseNode_triggerNode_1",
      "type": "defaultEdge",
      "source": "addNode_346",
      "target": "responseNode_triggerNode_1",
      "sourceHandle": "bottom",
      "targetHandle": "top"
    },
    {
      "id": "response-trigger_triggerNode_1",
      "type": "responseEdge",
      "source": "triggerNode_1",
      "target": "responseNode_triggerNode_1",
      "sourceHandle": "to-response",
      "targetHandle": "from-trigger"
    }
  ],
  "status": "active",
  "created_at": "2026-03-05T05:38:16.330116+00:00"
};

export async function getNodesAndEdges(): Promise<{
    nodes: Record<string, any>[],
    edges: Record<string, any>[],
}> {
    return {
        nodes: flowConfig.nodes,
        edges: flowConfig.edges,
    }
}

export async function getFlowConfig(): Promise<Record<string, any>> {
    return flowConfig;
}