const flowConfig = {
  "id": "f989c3bc-da3c-4021-8b19-f527920ba0a4",
  "name": "Pitiful Eventide",
  "nodes": [
    {
      "id": "triggerNode_1",
      "data": {
        "modes": {},
        "nodeId": "graphqlNode",
        "values": {
          "nodeName": "API Request",
          "responeType": "realtime",
          "advance_schema": "{\"sampleInput\":\"string\"}"
        },
        "trigger": true
      },
      "type": "triggerNode",
      "measured": {
        "width": 216,
        "height": 93
      },
      "position": {
        "x": 225,
        "y": 0
      },
      "selected": false
    },
    {
      "id": "s3Node_436",
      "data": {
        "label": "dynamicNode node",
        "logic": [],
        "modes": {},
        "nodeId": "s3Node",
        "values": {
          "id": "s3Node_436",
          "action": "S3_GET_FILE",
          "bucket": "lamatic-test-934384776909-eu-north-1-an",
          "filePath": "https://lamatic-test-934384776909-eu-north-1-an.s3.eu-north-1.amazonaws.com/test.json",
          "nodeName": "S3",
          "folderPath": "",
          "maxResults": 100,
          "credentials": "ramandeep aws",
          "filePattern": ""
        }
      },
      "type": "dynamicNode",
      "measured": {
        "width": 216,
        "height": 93
      },
      "position": {
        "x": 225,
        "y": 130
      },
      "selected": true
    },
    {
      "id": "docClassifierNode_960",
      "data": {
        "label": "Doc Classifier",
        "modes": [],
        "nodeId": "docClassifierNode",
        "values": {
          "id": "docClassifierNode_960",
          "classes": [
            {
              "id": "cls_molgl2vy_om135",
              "label": "Index ",
              "description": "It will contain page number wise indexing of the pages. ",
              "identifiableFields": "Content"
            },
            {
              "id": "cls_molglr3x_13yn6",
              "label": "Chapters",
              "description": "This will have chapters and there description with all the details. ",
              "identifiableFields": ""
            }
          ],
          "nodeName": "Doc Classifier",
          "classifier": [
            {
              "label": "Invoice",
              "value": "docClassifierNode_960-addNode_547",
              "description": "This is for invoice generated by a billing system. "
            },
            {
              "label": "Classifier 2",
              "value": "docClassifierNode_960-addNode_346",
              "description": "This is for a loan approval document, "
            }
          ],
          "documentUrl": "https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://icseindia.org/document/sample.pdf&ved=2ahUKEwivm_qXyZWUAxX5TWwGHYVqKVoQFnoECAwQAQ&usg=AOvVaw38ZOMSmSTemy89FIqx9xIt",
          "ocrModelName": [
            {
              "type": "ocr/document",
              "params": {},
              "configName": "configA",
              "model_name": "mistral/mistral-ocr-latest-old",
              "credentialId": "23206267-db92-450c-a233-9f786f3fd6aa",
              "provider_name": "mistral",
              "credential_name": "mistralll"
            }
          ],
          "embeddingModelName": {
            "type": "embedder/text",
            "params": {},
            "model_name": "text-embedding-ada-002",
            "credentialId": "6aa2c475-ccfc-4041-82b5-514fc7b8c3fd",
            "provider_name": "openai",
            "credential_name": "OpenAI"
          },
          "enhanceDescriptions": true,
          "generativeModelName": [
            {
              "type": "generator/text",
              "params": {},
              "configName": "configA",
              "model_name": "gpt-4o-mini",
              "credentialId": "6aa2c475-ccfc-4041-82b5-514fc7b8c3fd",
              "provider_name": "openai",
              "credential_name": "OpenAI"
            }
          ]
        }
      },
      "type": "agentClassifierNode",
      "measured": {
        "width": 216,
        "height": 93
      },
      "position": {
        "x": 225,
        "y": 260
      },
      "selected": false
    },
    {
      "id": "addNode_547",
      "data": {
        "label": "addNode node",
        "modes": {},
        "nodeId": "addNode",
        "values": {},
        "condition": "Invoice"
      },
      "type": "addNode",
      "measured": {
        "width": 216,
        "height": 100
      },
      "position": {
        "x": 0,
        "y": 390
      }
    },
    {
      "id": "addNode_346",
      "data": {
        "label": "addNode node",
        "modes": {},
        "nodeId": "addNode",
        "values": {}
      },
      "type": "addNode",
      "measured": {
        "width": 216,
        "height": 100
      },
      "position": {
        "x": 450,
        "y": 390
      }
    },
    {
      "id": "responseNode_triggerNode_1",
      "data": {
        "label": "Response",
        "nodeId": "graphqlResponseNode",
        "values": {
          "headers": "{\"content-type\":\"application/json\"}",
          "retries": "0",
          "nodeName": "API Response",
          "webhookUrl": "",
          "retry_delay": "0",
          "outputMapping": "{}"
        },
        "condition": "Invoice",
        "isResponseNode": true
      },
      "type": "responseNode",
      "measured": {
        "width": 216,
        "height": 93
      },
      "position": {
        "x": 225,
        "y": 520
      }
    }
  ],
  "edges": [
    {
      "id": "docClassifierNode_960-addNode_547",
      "data": {
        "condition": "Invoice",
        "branchName": "Classifier 1"
      },
      "type": "agentClassifierEdge",
      "source": "docClassifierNode_960",
      "target": "addNode_547",
      "sourceHandle": "bottom",
      "targetHandle": "top"
    },
    {
      "id": "docClassifierNode_960-addNode_346",
      "data": {
        "condition": "Classifier 2",
        "branchName": "Classifier 2"
      },
      "type": "agentClassifierEdge",
      "source": "docClassifierNode_960",
      "target": "addNode_346",
      "sourceHandle": "bottom",
      "targetHandle": "top"
    },
    {
      "id": "addNode_547-responseNode_triggerNode_1",
      "type": "defaultEdge",
      "source": "addNode_547",
      "target": "responseNode_triggerNode_1",
      "sourceHandle": "bottom",
      "targetHandle": "top"
    },
    {
      "id": "addNode_346-responseNode_triggerNode_1",
      "type": "defaultEdge",
      "source": "addNode_346",
      "target": "responseNode_triggerNode_1",
      "sourceHandle": "bottom",
      "targetHandle": "top"
    },
    {
      "id": "triggerNode_1-s3Node_436",
      "type": "defaultEdge",
      "source": "triggerNode_1",
      "target": "s3Node_436",
      "sourceHandle": "bottom",
      "targetHandle": "top"
    },
    {
      "id": "s3Node_436-docClassifierNode_960",
      "type": "defaultEdge",
      "source": "s3Node_436",
      "target": "docClassifierNode_960",
      "sourceHandle": "bottom",
      "targetHandle": "top"
    },
    {
      "id": "response-trigger_triggerNode_1",
      "type": "responseEdge",
      "source": "triggerNode_1",
      "target": "responseNode_triggerNode_1",
      "sourceHandle": "to-response",
      "targetHandle": "from-trigger"
    }
  ],
  "status": "active",
  "created_at": "2026-03-05T05:38:16.330116+00:00"
};

export async function getNodesAndEdges(): Promise<{
    nodes: Record<string, any>[],
    edges: Record<string, any>[],
}> {
    return {
        nodes: flowConfig.nodes,
        edges: flowConfig.edges,
    }
}

export async function getFlowConfig(): Promise<Record<string, any>> {
    return flowConfig;
}